// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.0
//
// <auto-generated>
//
// Generated from file `order.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package io.mycat.ep.v1.order;

public class CartOrderInfo implements java.lang.Cloneable, java.io.Serializable
{
    public long userId;

    public String token;

    public String receiverName;

    public String receiverPhone;

    public String receiverProvince;

    public String receiverCity;

    public String receiverDistrict;

    public String receiverStreet;

    public String receiverStreetNumber;

    public String extraInfo;

    public long cartId;

    public CartOrderInfo()
    {
        token = "";
        receiverName = "";
        receiverPhone = "";
        receiverProvince = "";
        receiverCity = "";
        receiverDistrict = "";
        receiverStreet = "";
        receiverStreetNumber = "";
        extraInfo = "";
    }

    public CartOrderInfo(long userId, String token, String receiverName, String receiverPhone, String receiverProvince, String receiverCity, String receiverDistrict, String receiverStreet, String receiverStreetNumber, String extraInfo, long cartId)
    {
        this.userId = userId;
        this.token = token;
        this.receiverName = receiverName;
        this.receiverPhone = receiverPhone;
        this.receiverProvince = receiverProvince;
        this.receiverCity = receiverCity;
        this.receiverDistrict = receiverDistrict;
        this.receiverStreet = receiverStreet;
        this.receiverStreetNumber = receiverStreetNumber;
        this.extraInfo = extraInfo;
        this.cartId = cartId;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        CartOrderInfo _r = null;
        if(rhs instanceof CartOrderInfo)
        {
            _r = (CartOrderInfo)rhs;
        }

        if(_r != null)
        {
            if(userId != _r.userId)
            {
                return false;
            }
            if(token != _r.token)
            {
                if(token == null || _r.token == null || !token.equals(_r.token))
                {
                    return false;
                }
            }
            if(receiverName != _r.receiverName)
            {
                if(receiverName == null || _r.receiverName == null || !receiverName.equals(_r.receiverName))
                {
                    return false;
                }
            }
            if(receiverPhone != _r.receiverPhone)
            {
                if(receiverPhone == null || _r.receiverPhone == null || !receiverPhone.equals(_r.receiverPhone))
                {
                    return false;
                }
            }
            if(receiverProvince != _r.receiverProvince)
            {
                if(receiverProvince == null || _r.receiverProvince == null || !receiverProvince.equals(_r.receiverProvince))
                {
                    return false;
                }
            }
            if(receiverCity != _r.receiverCity)
            {
                if(receiverCity == null || _r.receiverCity == null || !receiverCity.equals(_r.receiverCity))
                {
                    return false;
                }
            }
            if(receiverDistrict != _r.receiverDistrict)
            {
                if(receiverDistrict == null || _r.receiverDistrict == null || !receiverDistrict.equals(_r.receiverDistrict))
                {
                    return false;
                }
            }
            if(receiverStreet != _r.receiverStreet)
            {
                if(receiverStreet == null || _r.receiverStreet == null || !receiverStreet.equals(_r.receiverStreet))
                {
                    return false;
                }
            }
            if(receiverStreetNumber != _r.receiverStreetNumber)
            {
                if(receiverStreetNumber == null || _r.receiverStreetNumber == null || !receiverStreetNumber.equals(_r.receiverStreetNumber))
                {
                    return false;
                }
            }
            if(extraInfo != _r.extraInfo)
            {
                if(extraInfo == null || _r.extraInfo == null || !extraInfo.equals(_r.extraInfo))
                {
                    return false;
                }
            }
            if(cartId != _r.cartId)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::order::CartOrderInfo");
        __h = IceInternal.HashUtil.hashAdd(__h, userId);
        __h = IceInternal.HashUtil.hashAdd(__h, token);
        __h = IceInternal.HashUtil.hashAdd(__h, receiverName);
        __h = IceInternal.HashUtil.hashAdd(__h, receiverPhone);
        __h = IceInternal.HashUtil.hashAdd(__h, receiverProvince);
        __h = IceInternal.HashUtil.hashAdd(__h, receiverCity);
        __h = IceInternal.HashUtil.hashAdd(__h, receiverDistrict);
        __h = IceInternal.HashUtil.hashAdd(__h, receiverStreet);
        __h = IceInternal.HashUtil.hashAdd(__h, receiverStreetNumber);
        __h = IceInternal.HashUtil.hashAdd(__h, extraInfo);
        __h = IceInternal.HashUtil.hashAdd(__h, cartId);
        return __h;
    }

    public CartOrderInfo
    clone()
    {
        CartOrderInfo c = null;
        try
        {
            c = (CartOrderInfo)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeLong(userId);
        __os.writeString(token);
        __os.writeString(receiverName);
        __os.writeString(receiverPhone);
        __os.writeString(receiverProvince);
        __os.writeString(receiverCity);
        __os.writeString(receiverDistrict);
        __os.writeString(receiverStreet);
        __os.writeString(receiverStreetNumber);
        __os.writeString(extraInfo);
        __os.writeLong(cartId);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        userId = __is.readLong();
        token = __is.readString();
        receiverName = __is.readString();
        receiverPhone = __is.readString();
        receiverProvince = __is.readString();
        receiverCity = __is.readString();
        receiverDistrict = __is.readString();
        receiverStreet = __is.readString();
        receiverStreetNumber = __is.readString();
        extraInfo = __is.readString();
        cartId = __is.readLong();
    }

    static public void
    __write(IceInternal.BasicStream __os, CartOrderInfo __v)
    {
        if(__v == null)
        {
            __nullMarshalValue.__write(__os);
        }
        else
        {
            __v.__write(__os);
        }
    }

    static public CartOrderInfo
    __read(IceInternal.BasicStream __is, CartOrderInfo __v)
    {
        if(__v == null)
        {
             __v = new CartOrderInfo();
        }
        __v.__read(__is);
        return __v;
    }
    
    private static final CartOrderInfo __nullMarshalValue = new CartOrderInfo();

    public static final long serialVersionUID = 1294329382L;
}
