// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.0
//
// <auto-generated>
//
// Generated from file `order.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package io.mycat.ep.v1.order;

public final class OrderedGoodsSeqHelper
{
    public static void
    write(IceInternal.BasicStream __os, OrderedGoods[] __v)
    {
        if(__v == null)
        {
            __os.writeSize(0);
        }
        else
        {
            __os.writeSize(__v.length);
            for(int __i0 = 0; __i0 < __v.length; __i0++)
            {
                OrderedGoods.__write(__os, __v[__i0]);
            }
        }
    }

    public static OrderedGoods[]
    read(IceInternal.BasicStream __is)
    {
        OrderedGoods[] __v;
        final int __len0 = __is.readAndCheckSeqSize(12);
        __v = new OrderedGoods[__len0];
        for(int __i0 = 0; __i0 < __len0; __i0++)
        {
            __v[__i0] = OrderedGoods.__read(__is, __v[__i0]);
        }
        return __v;
    }
}
