// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.0
//
// <auto-generated>
//
// Generated from file `order.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package io.mycat.ep.v1.order;

public interface OrderHandlerPrx extends Ice.ObjectPrx
{
    public OrderResult makeOrder(OrderInfo info);

    public OrderResult makeOrder(OrderInfo info, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_makeOrder(OrderInfo info);

    public Ice.AsyncResult begin_makeOrder(OrderInfo info, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_makeOrder(OrderInfo info, Ice.Callback __cb);

    public Ice.AsyncResult begin_makeOrder(OrderInfo info, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_makeOrder(OrderInfo info, Callback_OrderHandler_makeOrder __cb);

    public Ice.AsyncResult begin_makeOrder(OrderInfo info, java.util.Map<String, String> __ctx, Callback_OrderHandler_makeOrder __cb);

    public Ice.AsyncResult begin_makeOrder(OrderInfo info, 
                                           IceInternal.Functional_GenericCallback1<OrderResult> __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_makeOrder(OrderInfo info, 
                                           IceInternal.Functional_GenericCallback1<OrderResult> __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_makeOrder(OrderInfo info, 
                                           java.util.Map<String, String> __ctx, 
                                           IceInternal.Functional_GenericCallback1<OrderResult> __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_makeOrder(OrderInfo info, 
                                           java.util.Map<String, String> __ctx, 
                                           IceInternal.Functional_GenericCallback1<OrderResult> __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb);

    public OrderResult end_makeOrder(Ice.AsyncResult __result);

    public OrderResult makeOrderFromCart(CartOrderInfo info);

    public OrderResult makeOrderFromCart(CartOrderInfo info, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_makeOrderFromCart(CartOrderInfo info);

    public Ice.AsyncResult begin_makeOrderFromCart(CartOrderInfo info, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_makeOrderFromCart(CartOrderInfo info, Ice.Callback __cb);

    public Ice.AsyncResult begin_makeOrderFromCart(CartOrderInfo info, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_makeOrderFromCart(CartOrderInfo info, Callback_OrderHandler_makeOrderFromCart __cb);

    public Ice.AsyncResult begin_makeOrderFromCart(CartOrderInfo info, java.util.Map<String, String> __ctx, Callback_OrderHandler_makeOrderFromCart __cb);

    public Ice.AsyncResult begin_makeOrderFromCart(CartOrderInfo info, 
                                                   IceInternal.Functional_GenericCallback1<OrderResult> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_makeOrderFromCart(CartOrderInfo info, 
                                                   IceInternal.Functional_GenericCallback1<OrderResult> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                   IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_makeOrderFromCart(CartOrderInfo info, 
                                                   java.util.Map<String, String> __ctx, 
                                                   IceInternal.Functional_GenericCallback1<OrderResult> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_makeOrderFromCart(CartOrderInfo info, 
                                                   java.util.Map<String, String> __ctx, 
                                                   IceInternal.Functional_GenericCallback1<OrderResult> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                   IceInternal.Functional_BoolCallback __sentCb);

    public OrderResult end_makeOrderFromCart(Ice.AsyncResult __result);
}
