// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.0
//
// <auto-generated>
//
// Generated from file `User.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package io.mycat.ep.v1.user;

public interface UserHandlerPrx extends Ice.ObjectPrx
{
    public UserSession regist(ClientInfo info);

    public UserSession regist(ClientInfo info, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_regist(ClientInfo info);

    public Ice.AsyncResult begin_regist(ClientInfo info, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_regist(ClientInfo info, Ice.Callback __cb);

    public Ice.AsyncResult begin_regist(ClientInfo info, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_regist(ClientInfo info, Callback_UserHandler_regist __cb);

    public Ice.AsyncResult begin_regist(ClientInfo info, java.util.Map<String, String> __ctx, Callback_UserHandler_regist __cb);

    public Ice.AsyncResult begin_regist(ClientInfo info, 
                                        IceInternal.Functional_GenericCallback1<UserSession> __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_regist(ClientInfo info, 
                                        IceInternal.Functional_GenericCallback1<UserSession> __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_regist(ClientInfo info, 
                                        java.util.Map<String, String> __ctx, 
                                        IceInternal.Functional_GenericCallback1<UserSession> __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_regist(ClientInfo info, 
                                        java.util.Map<String, String> __ctx, 
                                        IceInternal.Functional_GenericCallback1<UserSession> __responseCb, 
                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                        IceInternal.Functional_BoolCallback __sentCb);

    public UserSession end_regist(Ice.AsyncResult __result);

    public UserCommonResult sendSMSCode(String phone);

    public UserCommonResult sendSMSCode(String phone, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sendSMSCode(String phone);

    public Ice.AsyncResult begin_sendSMSCode(String phone, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sendSMSCode(String phone, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendSMSCode(String phone, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendSMSCode(String phone, Callback_UserHandler_sendSMSCode __cb);

    public Ice.AsyncResult begin_sendSMSCode(String phone, java.util.Map<String, String> __ctx, Callback_UserHandler_sendSMSCode __cb);

    public Ice.AsyncResult begin_sendSMSCode(String phone, 
                                             IceInternal.Functional_GenericCallback1<UserCommonResult> __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_sendSMSCode(String phone, 
                                             IceInternal.Functional_GenericCallback1<UserCommonResult> __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                             IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_sendSMSCode(String phone, 
                                             java.util.Map<String, String> __ctx, 
                                             IceInternal.Functional_GenericCallback1<UserCommonResult> __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_sendSMSCode(String phone, 
                                             java.util.Map<String, String> __ctx, 
                                             IceInternal.Functional_GenericCallback1<UserCommonResult> __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                             IceInternal.Functional_BoolCallback __sentCb);

    public UserCommonResult end_sendSMSCode(Ice.AsyncResult __result);

    public UserCommonResult changePassword(long userId, String smsCode, String newPassword);

    public UserCommonResult changePassword(long userId, String smsCode, String newPassword, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_changePassword(long userId, String smsCode, String newPassword);

    public Ice.AsyncResult begin_changePassword(long userId, String smsCode, String newPassword, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_changePassword(long userId, String smsCode, String newPassword, Ice.Callback __cb);

    public Ice.AsyncResult begin_changePassword(long userId, String smsCode, String newPassword, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_changePassword(long userId, String smsCode, String newPassword, Callback_UserHandler_changePassword __cb);

    public Ice.AsyncResult begin_changePassword(long userId, String smsCode, String newPassword, java.util.Map<String, String> __ctx, Callback_UserHandler_changePassword __cb);

    public Ice.AsyncResult begin_changePassword(long userId, 
                                                String smsCode, 
                                                String newPassword, 
                                                IceInternal.Functional_GenericCallback1<UserCommonResult> __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_changePassword(long userId, 
                                                String smsCode, 
                                                String newPassword, 
                                                IceInternal.Functional_GenericCallback1<UserCommonResult> __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_changePassword(long userId, 
                                                String smsCode, 
                                                String newPassword, 
                                                java.util.Map<String, String> __ctx, 
                                                IceInternal.Functional_GenericCallback1<UserCommonResult> __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_changePassword(long userId, 
                                                String smsCode, 
                                                String newPassword, 
                                                java.util.Map<String, String> __ctx, 
                                                IceInternal.Functional_GenericCallback1<UserCommonResult> __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb);

    public UserCommonResult end_changePassword(Ice.AsyncResult __result);

    public UserSession login(ClientInfo info);

    public UserSession login(ClientInfo info, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_login(ClientInfo info);

    public Ice.AsyncResult begin_login(ClientInfo info, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_login(ClientInfo info, Ice.Callback __cb);

    public Ice.AsyncResult begin_login(ClientInfo info, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_login(ClientInfo info, Callback_UserHandler_login __cb);

    public Ice.AsyncResult begin_login(ClientInfo info, java.util.Map<String, String> __ctx, Callback_UserHandler_login __cb);

    public Ice.AsyncResult begin_login(ClientInfo info, 
                                       IceInternal.Functional_GenericCallback1<UserSession> __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_login(ClientInfo info, 
                                       IceInternal.Functional_GenericCallback1<UserSession> __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_login(ClientInfo info, 
                                       java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_GenericCallback1<UserSession> __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_login(ClientInfo info, 
                                       java.util.Map<String, String> __ctx, 
                                       IceInternal.Functional_GenericCallback1<UserSession> __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb);

    public UserSession end_login(Ice.AsyncResult __result);
}
