// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.0
//
// <auto-generated>
//
// Generated from file `receiver.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package io.mycat.ep.v1.receiver;

public interface PurchaseReceiverHandlerPrx extends Ice.ObjectPrx
{
    public ReceiverResult queryPurchaseReceivers(ReceiverQuery query);

    public ReceiverResult queryPurchaseReceivers(ReceiverQuery query, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_queryPurchaseReceivers(ReceiverQuery query);

    public Ice.AsyncResult begin_queryPurchaseReceivers(ReceiverQuery query, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_queryPurchaseReceivers(ReceiverQuery query, Ice.Callback __cb);

    public Ice.AsyncResult begin_queryPurchaseReceivers(ReceiverQuery query, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_queryPurchaseReceivers(ReceiverQuery query, Callback_PurchaseReceiverHandler_queryPurchaseReceivers __cb);

    public Ice.AsyncResult begin_queryPurchaseReceivers(ReceiverQuery query, java.util.Map<String, String> __ctx, Callback_PurchaseReceiverHandler_queryPurchaseReceivers __cb);

    public Ice.AsyncResult begin_queryPurchaseReceivers(ReceiverQuery query, 
                                                        IceInternal.Functional_GenericCallback1<ReceiverResult> __responseCb, 
                                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_queryPurchaseReceivers(ReceiverQuery query, 
                                                        IceInternal.Functional_GenericCallback1<ReceiverResult> __responseCb, 
                                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                        IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_queryPurchaseReceivers(ReceiverQuery query, 
                                                        java.util.Map<String, String> __ctx, 
                                                        IceInternal.Functional_GenericCallback1<ReceiverResult> __responseCb, 
                                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_queryPurchaseReceivers(ReceiverQuery query, 
                                                        java.util.Map<String, String> __ctx, 
                                                        IceInternal.Functional_GenericCallback1<ReceiverResult> __responseCb, 
                                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                        IceInternal.Functional_BoolCallback __sentCb);

    public ReceiverResult end_queryPurchaseReceivers(Ice.AsyncResult __result);
}
