// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.0
//
// <auto-generated>
//
// Generated from file `receiver.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package io.mycat.ep.v1.receiver;

public final class PurchaseReceiverHandlerPrxHelper extends Ice.ObjectPrxHelperBase implements PurchaseReceiverHandlerPrx
{
    private static final String __queryPurchaseReceivers_name = "queryPurchaseReceivers";

    public ReceiverResult queryPurchaseReceivers(ReceiverQuery query)
    {
        return queryPurchaseReceivers(query, null, false);
    }

    public ReceiverResult queryPurchaseReceivers(ReceiverQuery query, java.util.Map<String, String> __ctx)
    {
        return queryPurchaseReceivers(query, __ctx, true);
    }

    private ReceiverResult queryPurchaseReceivers(ReceiverQuery query, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__queryPurchaseReceivers_name);
        return end_queryPurchaseReceivers(begin_queryPurchaseReceivers(query, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_queryPurchaseReceivers(ReceiverQuery query)
    {
        return begin_queryPurchaseReceivers(query, null, false, false, null);
    }

    public Ice.AsyncResult begin_queryPurchaseReceivers(ReceiverQuery query, java.util.Map<String, String> __ctx)
    {
        return begin_queryPurchaseReceivers(query, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_queryPurchaseReceivers(ReceiverQuery query, Ice.Callback __cb)
    {
        return begin_queryPurchaseReceivers(query, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_queryPurchaseReceivers(ReceiverQuery query, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_queryPurchaseReceivers(query, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_queryPurchaseReceivers(ReceiverQuery query, Callback_PurchaseReceiverHandler_queryPurchaseReceivers __cb)
    {
        return begin_queryPurchaseReceivers(query, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_queryPurchaseReceivers(ReceiverQuery query, java.util.Map<String, String> __ctx, Callback_PurchaseReceiverHandler_queryPurchaseReceivers __cb)
    {
        return begin_queryPurchaseReceivers(query, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_queryPurchaseReceivers(ReceiverQuery query, 
                                                        IceInternal.Functional_GenericCallback1<ReceiverResult> __responseCb, 
                                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_queryPurchaseReceivers(query, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_queryPurchaseReceivers(ReceiverQuery query, 
                                                        IceInternal.Functional_GenericCallback1<ReceiverResult> __responseCb, 
                                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                        IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_queryPurchaseReceivers(query, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_queryPurchaseReceivers(ReceiverQuery query, 
                                                        java.util.Map<String, String> __ctx, 
                                                        IceInternal.Functional_GenericCallback1<ReceiverResult> __responseCb, 
                                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_queryPurchaseReceivers(query, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_queryPurchaseReceivers(ReceiverQuery query, 
                                                        java.util.Map<String, String> __ctx, 
                                                        IceInternal.Functional_GenericCallback1<ReceiverResult> __responseCb, 
                                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                        IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_queryPurchaseReceivers(query, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_queryPurchaseReceivers(ReceiverQuery query, 
                                                         java.util.Map<String, String> __ctx, 
                                                         boolean __explicitCtx, 
                                                         boolean __synchronous, 
                                                         IceInternal.Functional_GenericCallback1<ReceiverResult> __responseCb, 
                                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                         IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_queryPurchaseReceivers(query, __ctx, __explicitCtx, __synchronous, 
                                            new IceInternal.Functional_TwowayCallbackArg1<io.mycat.ep.v1.receiver.ReceiverResult>(__responseCb, __exceptionCb, __sentCb)
                                                {
                                                    public final void __completed(Ice.AsyncResult __result)
                                                    {
                                                        PurchaseReceiverHandlerPrxHelper.__queryPurchaseReceivers_completed(this, __result);
                                                    }
                                                });
    }

    private Ice.AsyncResult begin_queryPurchaseReceivers(ReceiverQuery query, 
                                                         java.util.Map<String, String> __ctx, 
                                                         boolean __explicitCtx, 
                                                         boolean __synchronous, 
                                                         IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__queryPurchaseReceivers_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__queryPurchaseReceivers_name, __cb);
        try
        {
            __result.prepare(__queryPurchaseReceivers_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            ReceiverQuery.__write(__os, query);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public ReceiverResult end_queryPurchaseReceivers(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __queryPurchaseReceivers_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            ReceiverResult __ret = null;
            __ret = ReceiverResult.__read(__is, __ret);
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __queryPurchaseReceivers_completed(Ice.TwowayCallbackArg1<ReceiverResult> __cb, Ice.AsyncResult __result)
    {
        io.mycat.ep.v1.receiver.PurchaseReceiverHandlerPrx __proxy = (io.mycat.ep.v1.receiver.PurchaseReceiverHandlerPrx)__result.getProxy();
        ReceiverResult __ret = null;
        try
        {
            __ret = __proxy.end_queryPurchaseReceivers(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    public static PurchaseReceiverHandlerPrx checkedCast(Ice.ObjectPrx __obj)
    {
        return checkedCastImpl(__obj, ice_staticId(), PurchaseReceiverHandlerPrx.class, PurchaseReceiverHandlerPrxHelper.class);
    }

    public static PurchaseReceiverHandlerPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __ctx, ice_staticId(), PurchaseReceiverHandlerPrx.class, PurchaseReceiverHandlerPrxHelper.class);
    }

    public static PurchaseReceiverHandlerPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return checkedCastImpl(__obj, __facet, ice_staticId(), PurchaseReceiverHandlerPrx.class, PurchaseReceiverHandlerPrxHelper.class);
    }

    public static PurchaseReceiverHandlerPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __facet, __ctx, ice_staticId(), PurchaseReceiverHandlerPrx.class, PurchaseReceiverHandlerPrxHelper.class);
    }

    public static PurchaseReceiverHandlerPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        return uncheckedCastImpl(__obj, PurchaseReceiverHandlerPrx.class, PurchaseReceiverHandlerPrxHelper.class);
    }

    public static PurchaseReceiverHandlerPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return uncheckedCastImpl(__obj, __facet, PurchaseReceiverHandlerPrx.class, PurchaseReceiverHandlerPrxHelper.class);
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::receiver::PurchaseReceiverHandler"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    public static void __write(IceInternal.BasicStream __os, PurchaseReceiverHandlerPrx v)
    {
        __os.writeProxy(v);
    }

    public static PurchaseReceiverHandlerPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            PurchaseReceiverHandlerPrxHelper result = new PurchaseReceiverHandlerPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
