// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.0
//
// <auto-generated>
//
// Generated from file `receiver.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package io.mycat.ep.v1.receiver;

public final class ReceiverSeqHelper
{
    public static void
    write(IceInternal.BasicStream __os, PurchaseReceiver[] __v)
    {
        if(__v == null)
        {
            __os.writeSize(0);
        }
        else
        {
            __os.writeSize(__v.length);
            for(int __i0 = 0; __i0 < __v.length; __i0++)
            {
                PurchaseReceiver.__write(__os, __v[__i0]);
            }
        }
    }

    public static PurchaseReceiver[]
    read(IceInternal.BasicStream __is)
    {
        PurchaseReceiver[] __v;
        final int __len0 = __is.readAndCheckSeqSize(25);
        __v = new PurchaseReceiver[__len0];
        for(int __i0 = 0; __i0 < __len0; __i0++)
        {
            __v[__i0] = PurchaseReceiver.__read(__is, __v[__i0]);
        }
        return __v;
    }
}
