// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.0
//
// <auto-generated>
//
// Generated from file `goods.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package io.mycat.ep.v1.goods.stock;

public class StorageChange implements java.lang.Cloneable, java.io.Serializable
{
    public long userId;

    public String token;

    public long goodsId;

    public int amount;

    public StorageChange()
    {
        token = "";
    }

    public StorageChange(long userId, String token, long goodsId, int amount)
    {
        this.userId = userId;
        this.token = token;
        this.goodsId = goodsId;
        this.amount = amount;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        StorageChange _r = null;
        if(rhs instanceof StorageChange)
        {
            _r = (StorageChange)rhs;
        }

        if(_r != null)
        {
            if(userId != _r.userId)
            {
                return false;
            }
            if(token != _r.token)
            {
                if(token == null || _r.token == null || !token.equals(_r.token))
                {
                    return false;
                }
            }
            if(goodsId != _r.goodsId)
            {
                return false;
            }
            if(amount != _r.amount)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::goods::stock::StorageChange");
        __h = IceInternal.HashUtil.hashAdd(__h, userId);
        __h = IceInternal.HashUtil.hashAdd(__h, token);
        __h = IceInternal.HashUtil.hashAdd(__h, goodsId);
        __h = IceInternal.HashUtil.hashAdd(__h, amount);
        return __h;
    }

    public StorageChange
    clone()
    {
        StorageChange c = null;
        try
        {
            c = (StorageChange)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeLong(userId);
        __os.writeString(token);
        __os.writeLong(goodsId);
        __os.writeInt(amount);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        userId = __is.readLong();
        token = __is.readString();
        goodsId = __is.readLong();
        amount = __is.readInt();
    }

    static public void
    __write(IceInternal.BasicStream __os, StorageChange __v)
    {
        if(__v == null)
        {
            __nullMarshalValue.__write(__os);
        }
        else
        {
            __v.__write(__os);
        }
    }

    static public StorageChange
    __read(IceInternal.BasicStream __is, StorageChange __v)
    {
        if(__v == null)
        {
             __v = new StorageChange();
        }
        __v.__read(__is);
        return __v;
    }
    
    private static final StorageChange __nullMarshalValue = new StorageChange();

    public static final long serialVersionUID = -2060091278L;
}
