// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.0
//
// <auto-generated>
//
// Generated from file `goods.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package io.mycat.ep.v1.goods.stock;

public class StorageAmount implements java.lang.Cloneable, java.io.Serializable
{
    public int status;

    public int amount;

    public StorageAmount()
    {
    }

    public StorageAmount(int status, int amount)
    {
        this.status = status;
        this.amount = amount;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        StorageAmount _r = null;
        if(rhs instanceof StorageAmount)
        {
            _r = (StorageAmount)rhs;
        }

        if(_r != null)
        {
            if(status != _r.status)
            {
                return false;
            }
            if(amount != _r.amount)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::goods::stock::StorageAmount");
        __h = IceInternal.HashUtil.hashAdd(__h, status);
        __h = IceInternal.HashUtil.hashAdd(__h, amount);
        return __h;
    }

    public StorageAmount
    clone()
    {
        StorageAmount c = null;
        try
        {
            c = (StorageAmount)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeInt(status);
        __os.writeInt(amount);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        status = __is.readInt();
        amount = __is.readInt();
    }

    static public void
    __write(IceInternal.BasicStream __os, StorageAmount __v)
    {
        if(__v == null)
        {
            __nullMarshalValue.__write(__os);
        }
        else
        {
            __v.__write(__os);
        }
    }

    static public StorageAmount
    __read(IceInternal.BasicStream __is, StorageAmount __v)
    {
        if(__v == null)
        {
             __v = new StorageAmount();
        }
        __v.__read(__is);
        return __v;
    }
    
    private static final StorageAmount __nullMarshalValue = new StorageAmount();

    public static final long serialVersionUID = 1166408214L;
}
