// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.0
//
// <auto-generated>
//
// Generated from file `goods.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package io.mycat.ep.v1.goods;

public final class GoodsHandlerHolder extends Ice.ObjectHolderBase<GoodsHandler>
{
    public
    GoodsHandlerHolder()
    {
    }

    public
    GoodsHandlerHolder(GoodsHandler value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        if(v == null || v instanceof GoodsHandler)
        {
            value = (GoodsHandler)v;
        }
        else
        {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type()
    {
        return _GoodsHandlerDisp.ice_staticId();
    }
}
