// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.0
//
// <auto-generated>
//
// Generated from file `goods.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package io.mycat.ep.v1.goods;

public interface GoodsHandlerPrx extends Ice.ObjectPrx
{
    public GoodsPriceQueryResult queryGoodsPrice(GoodsPriceQuery query);

    public GoodsPriceQueryResult queryGoodsPrice(GoodsPriceQuery query, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_queryGoodsPrice(GoodsPriceQuery query);

    public Ice.AsyncResult begin_queryGoodsPrice(GoodsPriceQuery query, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_queryGoodsPrice(GoodsPriceQuery query, Ice.Callback __cb);

    public Ice.AsyncResult begin_queryGoodsPrice(GoodsPriceQuery query, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_queryGoodsPrice(GoodsPriceQuery query, Callback_GoodsHandler_queryGoodsPrice __cb);

    public Ice.AsyncResult begin_queryGoodsPrice(GoodsPriceQuery query, java.util.Map<String, String> __ctx, Callback_GoodsHandler_queryGoodsPrice __cb);

    public Ice.AsyncResult begin_queryGoodsPrice(GoodsPriceQuery query, 
                                                 IceInternal.Functional_GenericCallback1<GoodsPriceQueryResult> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_queryGoodsPrice(GoodsPriceQuery query, 
                                                 IceInternal.Functional_GenericCallback1<GoodsPriceQueryResult> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                 IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_queryGoodsPrice(GoodsPriceQuery query, 
                                                 java.util.Map<String, String> __ctx, 
                                                 IceInternal.Functional_GenericCallback1<GoodsPriceQueryResult> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_queryGoodsPrice(GoodsPriceQuery query, 
                                                 java.util.Map<String, String> __ctx, 
                                                 IceInternal.Functional_GenericCallback1<GoodsPriceQueryResult> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                 IceInternal.Functional_BoolCallback __sentCb);

    public GoodsPriceQueryResult end_queryGoodsPrice(Ice.AsyncResult __result);
}
