// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.0
//
// <auto-generated>
//
// Generated from file `flashsale.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package io.mycat.ep.v1.flashsale;

public class FlashSaleResult implements java.lang.Cloneable, java.io.Serializable
{
    public int status;

    public long flashSaleId;

    public String pass;

    public long goodsId;

    public int amount;

    public FlashSaleResult()
    {
        pass = "";
        amount = 1;
    }

    public FlashSaleResult(int status, long flashSaleId, String pass, long goodsId, int amount)
    {
        this.status = status;
        this.flashSaleId = flashSaleId;
        this.pass = pass;
        this.goodsId = goodsId;
        this.amount = amount;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        FlashSaleResult _r = null;
        if(rhs instanceof FlashSaleResult)
        {
            _r = (FlashSaleResult)rhs;
        }

        if(_r != null)
        {
            if(status != _r.status)
            {
                return false;
            }
            if(flashSaleId != _r.flashSaleId)
            {
                return false;
            }
            if(pass != _r.pass)
            {
                if(pass == null || _r.pass == null || !pass.equals(_r.pass))
                {
                    return false;
                }
            }
            if(goodsId != _r.goodsId)
            {
                return false;
            }
            if(amount != _r.amount)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::flashsale::FlashSaleResult");
        __h = IceInternal.HashUtil.hashAdd(__h, status);
        __h = IceInternal.HashUtil.hashAdd(__h, flashSaleId);
        __h = IceInternal.HashUtil.hashAdd(__h, pass);
        __h = IceInternal.HashUtil.hashAdd(__h, goodsId);
        __h = IceInternal.HashUtil.hashAdd(__h, amount);
        return __h;
    }

    public FlashSaleResult
    clone()
    {
        FlashSaleResult c = null;
        try
        {
            c = (FlashSaleResult)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeInt(status);
        __os.writeLong(flashSaleId);
        __os.writeString(pass);
        __os.writeLong(goodsId);
        __os.writeInt(amount);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        status = __is.readInt();
        flashSaleId = __is.readLong();
        pass = __is.readString();
        goodsId = __is.readLong();
        amount = __is.readInt();
    }

    static public void
    __write(IceInternal.BasicStream __os, FlashSaleResult __v)
    {
        if(__v == null)
        {
            __nullMarshalValue.__write(__os);
        }
        else
        {
            __v.__write(__os);
        }
    }

    static public FlashSaleResult
    __read(IceInternal.BasicStream __is, FlashSaleResult __v)
    {
        if(__v == null)
        {
             __v = new FlashSaleResult();
        }
        __v.__read(__is);
        return __v;
    }
    
    private static final FlashSaleResult __nullMarshalValue = new FlashSaleResult();

    public static final long serialVersionUID = 548950615L;
}
