// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.0
//
// <auto-generated>
//
// Generated from file `flashsale.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package io.mycat.ep.v1.flashsale;

public final class FlashBuyHandlerPrxHelper extends Ice.ObjectPrxHelperBase implements FlashBuyHandlerPrx
{
    private static final String __flashBuy_name = "flashBuy";

    public FlashSaleResult flashBuy(FlashSaleInfo sale)
    {
        return flashBuy(sale, null, false);
    }

    public FlashSaleResult flashBuy(FlashSaleInfo sale, java.util.Map<String, String> __ctx)
    {
        return flashBuy(sale, __ctx, true);
    }

    private FlashSaleResult flashBuy(FlashSaleInfo sale, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__flashBuy_name);
        return end_flashBuy(begin_flashBuy(sale, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_flashBuy(FlashSaleInfo sale)
    {
        return begin_flashBuy(sale, null, false, false, null);
    }

    public Ice.AsyncResult begin_flashBuy(FlashSaleInfo sale, java.util.Map<String, String> __ctx)
    {
        return begin_flashBuy(sale, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_flashBuy(FlashSaleInfo sale, Ice.Callback __cb)
    {
        return begin_flashBuy(sale, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_flashBuy(FlashSaleInfo sale, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_flashBuy(sale, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_flashBuy(FlashSaleInfo sale, Callback_FlashBuyHandler_flashBuy __cb)
    {
        return begin_flashBuy(sale, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_flashBuy(FlashSaleInfo sale, java.util.Map<String, String> __ctx, Callback_FlashBuyHandler_flashBuy __cb)
    {
        return begin_flashBuy(sale, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_flashBuy(FlashSaleInfo sale, 
                                          IceInternal.Functional_GenericCallback1<FlashSaleResult> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_flashBuy(sale, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_flashBuy(FlashSaleInfo sale, 
                                          IceInternal.Functional_GenericCallback1<FlashSaleResult> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_flashBuy(sale, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_flashBuy(FlashSaleInfo sale, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_GenericCallback1<FlashSaleResult> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_flashBuy(sale, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_flashBuy(FlashSaleInfo sale, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_GenericCallback1<FlashSaleResult> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_flashBuy(sale, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_flashBuy(FlashSaleInfo sale, 
                                           java.util.Map<String, String> __ctx, 
                                           boolean __explicitCtx, 
                                           boolean __synchronous, 
                                           IceInternal.Functional_GenericCallback1<FlashSaleResult> __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_flashBuy(sale, __ctx, __explicitCtx, __synchronous, 
                              new IceInternal.Functional_TwowayCallbackArg1<io.mycat.ep.v1.flashsale.FlashSaleResult>(__responseCb, __exceptionCb, __sentCb)
                                  {
                                      public final void __completed(Ice.AsyncResult __result)
                                      {
                                          FlashBuyHandlerPrxHelper.__flashBuy_completed(this, __result);
                                      }
                                  });
    }

    private Ice.AsyncResult begin_flashBuy(FlashSaleInfo sale, 
                                           java.util.Map<String, String> __ctx, 
                                           boolean __explicitCtx, 
                                           boolean __synchronous, 
                                           IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__flashBuy_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__flashBuy_name, __cb);
        try
        {
            __result.prepare(__flashBuy_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            FlashSaleInfo.__write(__os, sale);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public FlashSaleResult end_flashBuy(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __flashBuy_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            FlashSaleResult __ret = null;
            __ret = FlashSaleResult.__read(__is, __ret);
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __flashBuy_completed(Ice.TwowayCallbackArg1<FlashSaleResult> __cb, Ice.AsyncResult __result)
    {
        io.mycat.ep.v1.flashsale.FlashBuyHandlerPrx __proxy = (io.mycat.ep.v1.flashsale.FlashBuyHandlerPrx)__result.getProxy();
        FlashSaleResult __ret = null;
        try
        {
            __ret = __proxy.end_flashBuy(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    public static FlashBuyHandlerPrx checkedCast(Ice.ObjectPrx __obj)
    {
        return checkedCastImpl(__obj, ice_staticId(), FlashBuyHandlerPrx.class, FlashBuyHandlerPrxHelper.class);
    }

    public static FlashBuyHandlerPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __ctx, ice_staticId(), FlashBuyHandlerPrx.class, FlashBuyHandlerPrxHelper.class);
    }

    public static FlashBuyHandlerPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return checkedCastImpl(__obj, __facet, ice_staticId(), FlashBuyHandlerPrx.class, FlashBuyHandlerPrxHelper.class);
    }

    public static FlashBuyHandlerPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __facet, __ctx, ice_staticId(), FlashBuyHandlerPrx.class, FlashBuyHandlerPrxHelper.class);
    }

    public static FlashBuyHandlerPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        return uncheckedCastImpl(__obj, FlashBuyHandlerPrx.class, FlashBuyHandlerPrxHelper.class);
    }

    public static FlashBuyHandlerPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return uncheckedCastImpl(__obj, __facet, FlashBuyHandlerPrx.class, FlashBuyHandlerPrxHelper.class);
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::flashsale::FlashBuyHandler"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    public static void __write(IceInternal.BasicStream __os, FlashBuyHandlerPrx v)
    {
        __os.writeProxy(v);
    }

    public static FlashBuyHandlerPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            FlashBuyHandlerPrxHelper result = new FlashBuyHandlerPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
