// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.0
//
// <auto-generated>
//
// Generated from file `goods.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package io.mycat.ep.v1.goods;

public final class GoodsPriceSeqHolder extends Ice.Holder<GoodsPrice[]>
{
    public
    GoodsPriceSeqHolder()
    {
    }

    public
    GoodsPriceSeqHolder(GoodsPrice[] value)
    {
        super(value);
    }
}
