// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.0
//
// <auto-generated>
//
// Generated from file `goods.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package io.mycat.ep.v1.goods;

public class GoodsPrice implements java.lang.Cloneable, java.io.Serializable
{
    public long goodsId;

    public String price;

    public GoodsPrice()
    {
        price = "";
    }

    public GoodsPrice(long goodsId, String price)
    {
        this.goodsId = goodsId;
        this.price = price;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        GoodsPrice _r = null;
        if(rhs instanceof GoodsPrice)
        {
            _r = (GoodsPrice)rhs;
        }

        if(_r != null)
        {
            if(goodsId != _r.goodsId)
            {
                return false;
            }
            if(price != _r.price)
            {
                if(price == null || _r.price == null || !price.equals(_r.price))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::goods::GoodsPrice");
        __h = IceInternal.HashUtil.hashAdd(__h, goodsId);
        __h = IceInternal.HashUtil.hashAdd(__h, price);
        return __h;
    }

    public GoodsPrice
    clone()
    {
        GoodsPrice c = null;
        try
        {
            c = (GoodsPrice)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeLong(goodsId);
        __os.writeString(price);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        goodsId = __is.readLong();
        price = __is.readString();
    }

    static public void
    __write(IceInternal.BasicStream __os, GoodsPrice __v)
    {
        if(__v == null)
        {
            __nullMarshalValue.__write(__os);
        }
        else
        {
            __v.__write(__os);
        }
    }

    static public GoodsPrice
    __read(IceInternal.BasicStream __is, GoodsPrice __v)
    {
        if(__v == null)
        {
             __v = new GoodsPrice();
        }
        __v.__read(__is);
        return __v;
    }
    
    private static final GoodsPrice __nullMarshalValue = new GoodsPrice();

    public static final long serialVersionUID = -235381706L;
}
