// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.0
//
// <auto-generated>
//
// Generated from file `goods.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package io.mycat.ep.v1.goods;

public class GoodsPriceQueryResult implements java.lang.Cloneable, java.io.Serializable
{
    public int status;

    public GoodsPrice[] goodsPrice;

    public GoodsPriceQueryResult()
    {
    }

    public GoodsPriceQueryResult(int status, GoodsPrice[] goodsPrice)
    {
        this.status = status;
        this.goodsPrice = goodsPrice;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        GoodsPriceQueryResult _r = null;
        if(rhs instanceof GoodsPriceQueryResult)
        {
            _r = (GoodsPriceQueryResult)rhs;
        }

        if(_r != null)
        {
            if(status != _r.status)
            {
                return false;
            }
            if(!java.util.Arrays.equals(goodsPrice, _r.goodsPrice))
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::goods::GoodsPriceQueryResult");
        __h = IceInternal.HashUtil.hashAdd(__h, status);
        __h = IceInternal.HashUtil.hashAdd(__h, goodsPrice);
        return __h;
    }

    public GoodsPriceQueryResult
    clone()
    {
        GoodsPriceQueryResult c = null;
        try
        {
            c = (GoodsPriceQueryResult)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeInt(status);
        GoodsPriceSeqHelper.write(__os, goodsPrice);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        status = __is.readInt();
        goodsPrice = GoodsPriceSeqHelper.read(__is);
    }

    static public void
    __write(IceInternal.BasicStream __os, GoodsPriceQueryResult __v)
    {
        if(__v == null)
        {
            __nullMarshalValue.__write(__os);
        }
        else
        {
            __v.__write(__os);
        }
    }

    static public GoodsPriceQueryResult
    __read(IceInternal.BasicStream __is, GoodsPriceQueryResult __v)
    {
        if(__v == null)
        {
             __v = new GoodsPriceQueryResult();
        }
        __v.__read(__is);
        return __v;
    }
    
    private static final GoodsPriceQueryResult __nullMarshalValue = new GoodsPriceQueryResult();

    public static final long serialVersionUID = -336687028L;
}
