// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.0
//
// <auto-generated>
//
// Generated from file `goods.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package io.mycat.ep.v1.goods;

public final class GoodsHandlerPrxHelper extends Ice.ObjectPrxHelperBase implements GoodsHandlerPrx
{
    private static final String __queryGoodsPrice_name = "queryGoodsPrice";

    public GoodsPriceQueryResult queryGoodsPrice(GoodsPriceQuery query)
    {
        return queryGoodsPrice(query, null, false);
    }

    public GoodsPriceQueryResult queryGoodsPrice(GoodsPriceQuery query, java.util.Map<String, String> __ctx)
    {
        return queryGoodsPrice(query, __ctx, true);
    }

    private GoodsPriceQueryResult queryGoodsPrice(GoodsPriceQuery query, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__queryGoodsPrice_name);
        return end_queryGoodsPrice(begin_queryGoodsPrice(query, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_queryGoodsPrice(GoodsPriceQuery query)
    {
        return begin_queryGoodsPrice(query, null, false, false, null);
    }

    public Ice.AsyncResult begin_queryGoodsPrice(GoodsPriceQuery query, java.util.Map<String, String> __ctx)
    {
        return begin_queryGoodsPrice(query, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_queryGoodsPrice(GoodsPriceQuery query, Ice.Callback __cb)
    {
        return begin_queryGoodsPrice(query, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_queryGoodsPrice(GoodsPriceQuery query, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_queryGoodsPrice(query, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_queryGoodsPrice(GoodsPriceQuery query, Callback_GoodsHandler_queryGoodsPrice __cb)
    {
        return begin_queryGoodsPrice(query, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_queryGoodsPrice(GoodsPriceQuery query, java.util.Map<String, String> __ctx, Callback_GoodsHandler_queryGoodsPrice __cb)
    {
        return begin_queryGoodsPrice(query, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_queryGoodsPrice(GoodsPriceQuery query, 
                                                 IceInternal.Functional_GenericCallback1<GoodsPriceQueryResult> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_queryGoodsPrice(query, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_queryGoodsPrice(GoodsPriceQuery query, 
                                                 IceInternal.Functional_GenericCallback1<GoodsPriceQueryResult> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                 IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_queryGoodsPrice(query, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_queryGoodsPrice(GoodsPriceQuery query, 
                                                 java.util.Map<String, String> __ctx, 
                                                 IceInternal.Functional_GenericCallback1<GoodsPriceQueryResult> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_queryGoodsPrice(query, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_queryGoodsPrice(GoodsPriceQuery query, 
                                                 java.util.Map<String, String> __ctx, 
                                                 IceInternal.Functional_GenericCallback1<GoodsPriceQueryResult> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                 IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_queryGoodsPrice(query, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_queryGoodsPrice(GoodsPriceQuery query, 
                                                  java.util.Map<String, String> __ctx, 
                                                  boolean __explicitCtx, 
                                                  boolean __synchronous, 
                                                  IceInternal.Functional_GenericCallback1<GoodsPriceQueryResult> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_queryGoodsPrice(query, __ctx, __explicitCtx, __synchronous, 
                                     new IceInternal.Functional_TwowayCallbackArg1<io.mycat.ep.v1.goods.GoodsPriceQueryResult>(__responseCb, __exceptionCb, __sentCb)
                                         {
                                             public final void __completed(Ice.AsyncResult __result)
                                             {
                                                 GoodsHandlerPrxHelper.__queryGoodsPrice_completed(this, __result);
                                             }
                                         });
    }

    private Ice.AsyncResult begin_queryGoodsPrice(GoodsPriceQuery query, 
                                                  java.util.Map<String, String> __ctx, 
                                                  boolean __explicitCtx, 
                                                  boolean __synchronous, 
                                                  IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__queryGoodsPrice_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__queryGoodsPrice_name, __cb);
        try
        {
            __result.prepare(__queryGoodsPrice_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            GoodsPriceQuery.__write(__os, query);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public GoodsPriceQueryResult end_queryGoodsPrice(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __queryGoodsPrice_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            GoodsPriceQueryResult __ret = null;
            __ret = GoodsPriceQueryResult.__read(__is, __ret);
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __queryGoodsPrice_completed(Ice.TwowayCallbackArg1<GoodsPriceQueryResult> __cb, Ice.AsyncResult __result)
    {
        io.mycat.ep.v1.goods.GoodsHandlerPrx __proxy = (io.mycat.ep.v1.goods.GoodsHandlerPrx)__result.getProxy();
        GoodsPriceQueryResult __ret = null;
        try
        {
            __ret = __proxy.end_queryGoodsPrice(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    public static GoodsHandlerPrx checkedCast(Ice.ObjectPrx __obj)
    {
        return checkedCastImpl(__obj, ice_staticId(), GoodsHandlerPrx.class, GoodsHandlerPrxHelper.class);
    }

    public static GoodsHandlerPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __ctx, ice_staticId(), GoodsHandlerPrx.class, GoodsHandlerPrxHelper.class);
    }

    public static GoodsHandlerPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return checkedCastImpl(__obj, __facet, ice_staticId(), GoodsHandlerPrx.class, GoodsHandlerPrxHelper.class);
    }

    public static GoodsHandlerPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __facet, __ctx, ice_staticId(), GoodsHandlerPrx.class, GoodsHandlerPrxHelper.class);
    }

    public static GoodsHandlerPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        return uncheckedCastImpl(__obj, GoodsHandlerPrx.class, GoodsHandlerPrxHelper.class);
    }

    public static GoodsHandlerPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return uncheckedCastImpl(__obj, __facet, GoodsHandlerPrx.class, GoodsHandlerPrxHelper.class);
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::goods::GoodsHandler"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    public static void __write(IceInternal.BasicStream __os, GoodsHandlerPrx v)
    {
        __os.writeProxy(v);
    }

    public static GoodsHandlerPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            GoodsHandlerPrxHelper result = new GoodsHandlerPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
