// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.0
//
// <auto-generated>
//
// Generated from file `goods.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package io.mycat.ep.v1.goods.stock;

public interface GoodsStorageManageHandler extends Ice.Object,
                                                   _GoodsStorageManageHandlerOperations, _GoodsStorageManageHandlerOperationsNC
{
    public static final String ice_staticId = "::goods::stock::GoodsStorageManageHandler";

    public static final long serialVersionUID = 1191556957L;
}
