// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.0
//
// <auto-generated>
//
// Generated from file `flashsale.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package io.mycat.ep.v1.flashsale;

public class FlashSaleInfo implements java.lang.Cloneable, java.io.Serializable
{
    public long userId;

    public String token;

    public long goodsId;

    public FlashSaleInfo()
    {
        token = "";
    }

    public FlashSaleInfo(long userId, String token, long goodsId)
    {
        this.userId = userId;
        this.token = token;
        this.goodsId = goodsId;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        FlashSaleInfo _r = null;
        if(rhs instanceof FlashSaleInfo)
        {
            _r = (FlashSaleInfo)rhs;
        }

        if(_r != null)
        {
            if(userId != _r.userId)
            {
                return false;
            }
            if(token != _r.token)
            {
                if(token == null || _r.token == null || !token.equals(_r.token))
                {
                    return false;
                }
            }
            if(goodsId != _r.goodsId)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::flashsale::FlashSaleInfo");
        __h = IceInternal.HashUtil.hashAdd(__h, userId);
        __h = IceInternal.HashUtil.hashAdd(__h, token);
        __h = IceInternal.HashUtil.hashAdd(__h, goodsId);
        return __h;
    }

    public FlashSaleInfo
    clone()
    {
        FlashSaleInfo c = null;
        try
        {
            c = (FlashSaleInfo)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeLong(userId);
        __os.writeString(token);
        __os.writeLong(goodsId);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        userId = __is.readLong();
        token = __is.readString();
        goodsId = __is.readLong();
    }

    static public void
    __write(IceInternal.BasicStream __os, FlashSaleInfo __v)
    {
        if(__v == null)
        {
            __nullMarshalValue.__write(__os);
        }
        else
        {
            __v.__write(__os);
        }
    }

    static public FlashSaleInfo
    __read(IceInternal.BasicStream __is, FlashSaleInfo __v)
    {
        if(__v == null)
        {
             __v = new FlashSaleInfo();
        }
        __v.__read(__is);
        return __v;
    }
    
    private static final FlashSaleInfo __nullMarshalValue = new FlashSaleInfo();

    public static final long serialVersionUID = -1604454824L;
}
