// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.0
//
// <auto-generated>
//
// Generated from file `flashsale.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package io.mycat.ep.v1.flashsale;

public interface FlashBuyHandler extends Ice.Object,
                                         _FlashBuyHandlerOperations, _FlashBuyHandlerOperationsNC
{
    public static final String ice_staticId = "::flashsale::FlashBuyHandler";

    public static final long serialVersionUID = 1335255344L;
}
