// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.0
//
// <auto-generated>
//
// Generated from file `User.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package io.mycat.ep.v1.user.session;

public interface UserSessionHandlerPrx extends Ice.ObjectPrx
{
    public io.mycat.ep.v1.user.UserSession checkLoginStatus(long userId, String token);

    public io.mycat.ep.v1.user.UserSession checkLoginStatus(long userId, String token, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_checkLoginStatus(long userId, String token);

    public Ice.AsyncResult begin_checkLoginStatus(long userId, String token, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_checkLoginStatus(long userId, String token, Ice.Callback __cb);

    public Ice.AsyncResult begin_checkLoginStatus(long userId, String token, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_checkLoginStatus(long userId, String token, Callback_UserSessionHandler_checkLoginStatus __cb);

    public Ice.AsyncResult begin_checkLoginStatus(long userId, String token, java.util.Map<String, String> __ctx, Callback_UserSessionHandler_checkLoginStatus __cb);

    public Ice.AsyncResult begin_checkLoginStatus(long userId, 
                                                  String token, 
                                                  IceInternal.Functional_GenericCallback1<io.mycat.ep.v1.user.UserSession> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_checkLoginStatus(long userId, 
                                                  String token, 
                                                  IceInternal.Functional_GenericCallback1<io.mycat.ep.v1.user.UserSession> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_checkLoginStatus(long userId, 
                                                  String token, 
                                                  java.util.Map<String, String> __ctx, 
                                                  IceInternal.Functional_GenericCallback1<io.mycat.ep.v1.user.UserSession> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_checkLoginStatus(long userId, 
                                                  String token, 
                                                  java.util.Map<String, String> __ctx, 
                                                  IceInternal.Functional_GenericCallback1<io.mycat.ep.v1.user.UserSession> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb);

    public io.mycat.ep.v1.user.UserSession end_checkLoginStatus(Ice.AsyncResult __result);
}
