// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.0
//
// <auto-generated>
//
// Generated from file `User.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package io.mycat.ep.v1.user;

public interface UserHandler extends Ice.Object,
                                     _UserHandlerOperations, _UserHandlerOperationsNC
{
    public static final String ice_staticId = "::user::UserHandler";

    public static final long serialVersionUID = 1347898949L;
}
