// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.0
//
// <auto-generated>
//
// Generated from file `receiver.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package io.mycat.ep.v1.receiver;

public abstract class Callback_PurchaseReceiverHandler_queryPurchaseReceivers
    extends IceInternal.TwowayCallback implements Ice.TwowayCallbackArg1<io.mycat.ep.v1.receiver.ReceiverResult>
{
    public final void __completed(Ice.AsyncResult __result)
    {
        PurchaseReceiverHandlerPrxHelper.__queryPurchaseReceivers_completed(this, __result);
    }
}
