// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.0
//
// <auto-generated>
//
// Generated from file `receiver.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package io.mycat.ep.v1.receiver;

public class PurchaseReceiver implements java.lang.Cloneable, java.io.Serializable
{
    public long id;

    public long userId;

    public String name;

    public String phone;

    public String province;

    public String city;

    public String district;

    public String street;

    public String streetNumber;

    public String extraInfo;

    public boolean defaultReceiver;

    public PurchaseReceiver()
    {
        name = "";
        phone = "";
        province = "";
        city = "";
        district = "";
        street = "";
        streetNumber = "";
        extraInfo = "";
    }

    public PurchaseReceiver(long id, long userId, String name, String phone, String province, String city, String district, String street, String streetNumber, String extraInfo, boolean defaultReceiver)
    {
        this.id = id;
        this.userId = userId;
        this.name = name;
        this.phone = phone;
        this.province = province;
        this.city = city;
        this.district = district;
        this.street = street;
        this.streetNumber = streetNumber;
        this.extraInfo = extraInfo;
        this.defaultReceiver = defaultReceiver;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        PurchaseReceiver _r = null;
        if(rhs instanceof PurchaseReceiver)
        {
            _r = (PurchaseReceiver)rhs;
        }

        if(_r != null)
        {
            if(id != _r.id)
            {
                return false;
            }
            if(userId != _r.userId)
            {
                return false;
            }
            if(name != _r.name)
            {
                if(name == null || _r.name == null || !name.equals(_r.name))
                {
                    return false;
                }
            }
            if(phone != _r.phone)
            {
                if(phone == null || _r.phone == null || !phone.equals(_r.phone))
                {
                    return false;
                }
            }
            if(province != _r.province)
            {
                if(province == null || _r.province == null || !province.equals(_r.province))
                {
                    return false;
                }
            }
            if(city != _r.city)
            {
                if(city == null || _r.city == null || !city.equals(_r.city))
                {
                    return false;
                }
            }
            if(district != _r.district)
            {
                if(district == null || _r.district == null || !district.equals(_r.district))
                {
                    return false;
                }
            }
            if(street != _r.street)
            {
                if(street == null || _r.street == null || !street.equals(_r.street))
                {
                    return false;
                }
            }
            if(streetNumber != _r.streetNumber)
            {
                if(streetNumber == null || _r.streetNumber == null || !streetNumber.equals(_r.streetNumber))
                {
                    return false;
                }
            }
            if(extraInfo != _r.extraInfo)
            {
                if(extraInfo == null || _r.extraInfo == null || !extraInfo.equals(_r.extraInfo))
                {
                    return false;
                }
            }
            if(defaultReceiver != _r.defaultReceiver)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::receiver::PurchaseReceiver");
        __h = IceInternal.HashUtil.hashAdd(__h, id);
        __h = IceInternal.HashUtil.hashAdd(__h, userId);
        __h = IceInternal.HashUtil.hashAdd(__h, name);
        __h = IceInternal.HashUtil.hashAdd(__h, phone);
        __h = IceInternal.HashUtil.hashAdd(__h, province);
        __h = IceInternal.HashUtil.hashAdd(__h, city);
        __h = IceInternal.HashUtil.hashAdd(__h, district);
        __h = IceInternal.HashUtil.hashAdd(__h, street);
        __h = IceInternal.HashUtil.hashAdd(__h, streetNumber);
        __h = IceInternal.HashUtil.hashAdd(__h, extraInfo);
        __h = IceInternal.HashUtil.hashAdd(__h, defaultReceiver);
        return __h;
    }

    public PurchaseReceiver
    clone()
    {
        PurchaseReceiver c = null;
        try
        {
            c = (PurchaseReceiver)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeLong(id);
        __os.writeLong(userId);
        __os.writeString(name);
        __os.writeString(phone);
        __os.writeString(province);
        __os.writeString(city);
        __os.writeString(district);
        __os.writeString(street);
        __os.writeString(streetNumber);
        __os.writeString(extraInfo);
        __os.writeBool(defaultReceiver);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        id = __is.readLong();
        userId = __is.readLong();
        name = __is.readString();
        phone = __is.readString();
        province = __is.readString();
        city = __is.readString();
        district = __is.readString();
        street = __is.readString();
        streetNumber = __is.readString();
        extraInfo = __is.readString();
        defaultReceiver = __is.readBool();
    }

    static public void
    __write(IceInternal.BasicStream __os, PurchaseReceiver __v)
    {
        if(__v == null)
        {
            __nullMarshalValue.__write(__os);
        }
        else
        {
            __v.__write(__os);
        }
    }

    static public PurchaseReceiver
    __read(IceInternal.BasicStream __is, PurchaseReceiver __v)
    {
        if(__v == null)
        {
             __v = new PurchaseReceiver();
        }
        __v.__read(__is);
        return __v;
    }
    
    private static final PurchaseReceiver __nullMarshalValue = new PurchaseReceiver();

    public static final long serialVersionUID = 1063308179L;
}
