export ZSH=$HOME/.oh-my-zsh

plugins=(git git-extras svn mvn autojump yum supervisor)
ZSH_THEME="robbyrussell"
DISABLE_AUTO_UPDATE="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
HIST_STAMPS="yyyy-mm-dd"

export TIME_STYLE='+%y-%m-%d %H:%M'
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

source $ZSH/oh-my-zsh.sh

export PS1='[%{$fg[blue]%}%n%{$reset_color%}@%{$fg[yellow]%}%m%{$fg[cyan]%} %c%{$reset_color%}]%{$fg_bold[blue]%}$(git_prompt_info)%{$fg_bold[blue]%} % %{$reset_color%}'