// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.0
//
// <auto-generated>
//
// Generated from file `User.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package io.mycat.ep.v1.user.session;

public final class UserSessionHandlerPrxHolder
{
    public
    UserSessionHandlerPrxHolder()
    {
    }

    public
    UserSessionHandlerPrxHolder(UserSessionHandlerPrx value)
    {
        this.value = value;
    }

    public UserSessionHandlerPrx value;
}
