// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.0
//
// <auto-generated>
//
// Generated from file `User.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package io.mycat.ep.v1.session;

public class UserToken implements java.lang.Cloneable, java.io.Serializable
{
    public long userId;

    public String token;

    public UserToken()
    {
        token = "";
    }

    public UserToken(long userId, String token)
    {
        this.userId = userId;
        this.token = token;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        UserToken _r = null;
        if(rhs instanceof UserToken)
        {
            _r = (UserToken)rhs;
        }

        if(_r != null)
        {
            if(userId != _r.userId)
            {
                return false;
            }
            if(token != _r.token)
            {
                if(token == null || _r.token == null || !token.equals(_r.token))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::session::UserToken");
        __h = IceInternal.HashUtil.hashAdd(__h, userId);
        __h = IceInternal.HashUtil.hashAdd(__h, token);
        return __h;
    }

    public UserToken
    clone()
    {
        UserToken c = null;
        try
        {
            c = (UserToken)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeLong(userId);
        __os.writeString(token);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        userId = __is.readLong();
        token = __is.readString();
    }

    static public void
    __write(IceInternal.BasicStream __os, UserToken __v)
    {
        if(__v == null)
        {
            __nullMarshalValue.__write(__os);
        }
        else
        {
            __v.__write(__os);
        }
    }

    static public UserToken
    __read(IceInternal.BasicStream __is, UserToken __v)
    {
        if(__v == null)
        {
             __v = new UserToken();
        }
        __v.__read(__is);
        return __v;
    }
    
    private static final UserToken __nullMarshalValue = new UserToken();

    public static final long serialVersionUID = -1060886888L;
}
