// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.0
//
// <auto-generated>
//
// Generated from file `User.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package io.mycat.ep.v1.session;

public final class UserSessionHandlerPrxHelper extends Ice.ObjectPrxHelperBase implements UserSessionHandlerPrx
{
    private static final String __checkLoginStatus_name = "checkLoginStatus";

    public UserSessionCommonResult checkLoginStatus(UserToken token)
    {
        return checkLoginStatus(token, null, false);
    }

    public UserSessionCommonResult checkLoginStatus(UserToken token, java.util.Map<String, String> __ctx)
    {
        return checkLoginStatus(token, __ctx, true);
    }

    private UserSessionCommonResult checkLoginStatus(UserToken token, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__checkLoginStatus_name);
        return end_checkLoginStatus(begin_checkLoginStatus(token, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_checkLoginStatus(UserToken token)
    {
        return begin_checkLoginStatus(token, null, false, false, null);
    }

    public Ice.AsyncResult begin_checkLoginStatus(UserToken token, java.util.Map<String, String> __ctx)
    {
        return begin_checkLoginStatus(token, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_checkLoginStatus(UserToken token, Ice.Callback __cb)
    {
        return begin_checkLoginStatus(token, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_checkLoginStatus(UserToken token, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_checkLoginStatus(token, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_checkLoginStatus(UserToken token, Callback_UserSessionHandler_checkLoginStatus __cb)
    {
        return begin_checkLoginStatus(token, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_checkLoginStatus(UserToken token, java.util.Map<String, String> __ctx, Callback_UserSessionHandler_checkLoginStatus __cb)
    {
        return begin_checkLoginStatus(token, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_checkLoginStatus(UserToken token, 
                                                  IceInternal.Functional_GenericCallback1<UserSessionCommonResult> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_checkLoginStatus(token, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_checkLoginStatus(UserToken token, 
                                                  IceInternal.Functional_GenericCallback1<UserSessionCommonResult> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_checkLoginStatus(token, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_checkLoginStatus(UserToken token, 
                                                  java.util.Map<String, String> __ctx, 
                                                  IceInternal.Functional_GenericCallback1<UserSessionCommonResult> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_checkLoginStatus(token, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_checkLoginStatus(UserToken token, 
                                                  java.util.Map<String, String> __ctx, 
                                                  IceInternal.Functional_GenericCallback1<UserSessionCommonResult> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_checkLoginStatus(token, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_checkLoginStatus(UserToken token, 
                                                   java.util.Map<String, String> __ctx, 
                                                   boolean __explicitCtx, 
                                                   boolean __synchronous, 
                                                   IceInternal.Functional_GenericCallback1<UserSessionCommonResult> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                   IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_checkLoginStatus(token, __ctx, __explicitCtx, __synchronous, 
                                      new IceInternal.Functional_TwowayCallbackArg1<io.mycat.ep.v1.session.UserSessionCommonResult>(__responseCb, __exceptionCb, __sentCb)
                                          {
                                              public final void __completed(Ice.AsyncResult __result)
                                              {
                                                  UserSessionHandlerPrxHelper.__checkLoginStatus_completed(this, __result);
                                              }
                                          });
    }

    private Ice.AsyncResult begin_checkLoginStatus(UserToken token, 
                                                   java.util.Map<String, String> __ctx, 
                                                   boolean __explicitCtx, 
                                                   boolean __synchronous, 
                                                   IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__checkLoginStatus_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__checkLoginStatus_name, __cb);
        try
        {
            __result.prepare(__checkLoginStatus_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            UserToken.__write(__os, token);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public UserSessionCommonResult end_checkLoginStatus(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __checkLoginStatus_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            UserSessionCommonResult __ret = null;
            __ret = UserSessionCommonResult.__read(__is, __ret);
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __checkLoginStatus_completed(Ice.TwowayCallbackArg1<UserSessionCommonResult> __cb, Ice.AsyncResult __result)
    {
        io.mycat.ep.v1.session.UserSessionHandlerPrx __proxy = (io.mycat.ep.v1.session.UserSessionHandlerPrx)__result.getProxy();
        UserSessionCommonResult __ret = null;
        try
        {
            __ret = __proxy.end_checkLoginStatus(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    public static UserSessionHandlerPrx checkedCast(Ice.ObjectPrx __obj)
    {
        return checkedCastImpl(__obj, ice_staticId(), UserSessionHandlerPrx.class, UserSessionHandlerPrxHelper.class);
    }

    public static UserSessionHandlerPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __ctx, ice_staticId(), UserSessionHandlerPrx.class, UserSessionHandlerPrxHelper.class);
    }

    public static UserSessionHandlerPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return checkedCastImpl(__obj, __facet, ice_staticId(), UserSessionHandlerPrx.class, UserSessionHandlerPrxHelper.class);
    }

    public static UserSessionHandlerPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __facet, __ctx, ice_staticId(), UserSessionHandlerPrx.class, UserSessionHandlerPrxHelper.class);
    }

    public static UserSessionHandlerPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        return uncheckedCastImpl(__obj, UserSessionHandlerPrx.class, UserSessionHandlerPrxHelper.class);
    }

    public static UserSessionHandlerPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return uncheckedCastImpl(__obj, __facet, UserSessionHandlerPrx.class, UserSessionHandlerPrxHelper.class);
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::session::UserSessionHandler"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    public static void __write(IceInternal.BasicStream __os, UserSessionHandlerPrx v)
    {
        __os.writeProxy(v);
    }

    public static UserSessionHandlerPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            UserSessionHandlerPrxHelper result = new UserSessionHandlerPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
